### ISSUE TITLE
Speed mode low values.

### ISSUE THREAD

**Issue by rosenblat** [EmanuelFeru/hoverboard-firmware-hack-FOC#20]
Great project. Speed mode works well for my application but when the speed is small 1-7 the motor pauses between control cycle steps. Is there a way to reduce the pause time to get more continuous rotation in the low 1-7 speed range.

Thanks for sharing your work.

**Comment by EmanuelFeru** [comment]
Thanks @rosenblat . At very low speed is very challenging to get very smooth movement due to position error between hall sensors. We need very fancy estimations to be able to do it and as we are very limited computationally, it is not possible to implemented on this platform or requires a lot of effort. So unfortunately, I cannot implement this. Sorry.
Still, as a suggestion to get a more smooth movement without too many changes, redesign, etc.. you can  to switch to VOLTAGE_MODE bellow a certain low speed value. This should improve it. I hope it helps.
