### ISSUE TITLE
N_MOT_MAX is not working under  SIN_CTRL type

### ISSUE THREAD

**Issue by humble800** [EmanuelFeru/hoverboard-firmware-hack-FOC#205]
### Your System
- VARIANT: VARIANT_USART
- CONTROL TYPE: SIN_CTRL
- CONTROL MODE: VLT_MODE
- What is your application?
    - RC go kart.

### Issue
The sinusoidal mode doesn’t seem to limit the speed to the parameter specified by N_MOT_MAX.  When I use FOC_CTRL and TRQ_MODE, the motor RPM is indeed capped by N_MOT_MAX; so I believe the UART communication and wiring are set up correctly.

1.	Do I need to modify the main loop and implement some sort of PID loop to control the cmd2, such that the motor speed will be capped by N_MOT_MAX when control type is set to SIN_CTRL?
  
2.	Under the SIN_CTRL control type, are there differences between VLT_MODE and OPEN_MODE?

Thank you very much!

**Comment by EmanuelFeru** [comment]
1. For SIN_CTRL and COM_CTRL there is no speed control implemented. Thus N_NOT_MAX is neglected. You have to implement your own store control for that.
2. For all control types, Open mode will put the motor commands to 0 but will not disable the motors, meaning the MOSFETS will still need conducting. In general, for SIN_CTRL and COM_CTRL the SPD_MOD and VLT_MOD are neglected since it is always doing Voltage mode. Only OPEN_MODE is still considered in case of a non critical error.
