### ISSUE TITLE
Serial monitor output fail

### ISSUE THREAD

**Issue by phiberjenz** [EmanuelFeru/hoverboard-firmware-hack-FOC#33]
Hello Emanuel,

First of all, thank you very much for the hard work you´ve put into this.

I've tried building both the Hovercar and the ADC variant, and ADC variant is working fine. I don't seem to get the Hovercar variant working as expected though, the motors are spinning back and forth when potientiometer is in the middle (I guess this has something to do with the Torque mode?), and the brake won't work at all.

Still, to be able to debug this I would like to see some text in the serial monitor. I just get a lot of random characters and no text; this is so also for the ADC variant. Tried the NiklasFauth master fork and I get the text in the monitor just fine. I've tried digging into the codebase, but I can't see anything that's off.

Using following settings in Putty:
Baud rate: 115200
Data bits: 8
Stop bits: 1
No parity
Flow control: XON/XOFF

Do you have any idea what might be going on?

Tried disabling the "FEEDBACK_SERIAL_USART3 and enabled "DEBUG_SERIAL_USART3" but output is the same.

I have no sideboard connected at all.

Best regards,
Jens Nilsson

**Comment by EmanuelFeru** [comment]
Hello Jens,

Awesome that you are trying the Hovercar :)

_______
>  I don't seem to get the Hovercar variant working as expected though, the motors are spinning back and forth when potientiometer is in the middle (I guess this has something to do with the Torque mode?), and the brake won't work at all.

What kind of pots are you using, middle resting? Normally, Hovercar is expecting pots that rest at the lower bound. 
Also, you need to calibrate the pots min/max limits. Either manually (see [here](https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/95c10c9ba788de2bb88483276b7c03336fc31aa1/Inc/config.h#L212-L230)) or automatically by keeping pressed the Power button for more than 5 sec until you hear a beep, see more details here:
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/95c10c9ba788de2bb88483276b7c03336fc31aa1/Src/util.c#L399-L405

_______

> I just get a lot of random characters and no text; this is so also for the ADC variant. 

For debugging, you get gibberish because I am using a different baud rate. Change your monitor baud rate to `38400` and you will be fine. Or update your desired baud rate here:
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/95c10c9ba788de2bb88483276b7c03336fc31aa1/Inc/config.h#L397-L406

_______
> I have no sideboard connected at all.

If you are not using the Sideboard then comment out these 2 lines:
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/95c10c9ba788de2bb88483276b7c03336fc31aa1/Inc/config.h#L345-L346
_____

_______
PS: I wil be posting a video with the Hovercar build on Youtube. I already posted some videos in the **Telegram goup**. Feel free to join the group here: https://t.me/joinchat/BHWO_RKu2LT5ZxEkvUB8uw
