### ISSUE TITLE
Drive a motor smoothly slow

### ISSUE THREAD

**Issue by m-farahmand** [EmanuelFeru/hoverboard-firmware-hack-FOC#52]
Hi
I use this source for the wheelchair, It's very good with low noise but when I change the direction of the motor suddenly by the joystick mainboard has been turned off.
How can I make it smoother with the config file? 
Do I need to write my speed PID?

Thank you ...

**Comment by EmanuelFeru** [comment]
It turns off probably because you have to calibrate the battery voltage ADC reading (check this discussion https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/issues/51)

If your  want to drive the motors slowly then I recommend [selecting VOLTAGE_MODE in the config.h]{https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/blob/ea8507fc672f8843110d45546b8580f25376e7f4/Inc/config.h#L129)
